services:
  db:
    image: postgres:18-alpine
    container_name: crypto-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crypto_tracker
    ports:
      - "127.0.0.1:5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: